### ISSUE TITLE
Feature request: Preserve field comments

### ISSUE THREAD

**Issue by AlexDEVpro** [Tyriar/vscode-sort-lines#90] opened 2021-03-04 21:59 UTC
Example initial code:

     /**
     * This is field B.
     *
     * @memberof SomeClass
     */
    b = 2;

    /**
     * This is field A.
     *
     * @memberof SomeClass
     */
    a = 1;

Expected sort result:

    /**
     * This is field A.
     *
     * @memberof SomeClass
     */
    a = 1;
    
    /**
     * This is field B.
     *
     * @memberof SomeClass
     */
    b = 2;

The actual result:

     *
     *
     * @memberof SomeClass
     * @memberof SomeClass
     * This is field A.
     * This is field B.
     */
     */
    /**
    /**
    a = 1;
    b = 2;

**Comment by Tyriar** [comment] 2021-03-05 00:18
Closing this out as designed since language smarts like understanding comments and whitespace in languages are out of scope of this extension.

**Closed by Tyriar** 2021-03-05 00:18 UTC
